export type Icons =
  | "appointments.svg"
  | "arrow.svg"
  | "calendar.svg"
  | "cancelled.svg"
  | "check.svg"
  | "check-circle.svg"
  | "close.svg"
  | "email.svg"
  | "loader.svg"
  | "logo-full.svg"
  | "logo-icon.svg"
  | "MediMeet.svg"
  | "pending.svg"
  | "upload.svg"
  | "user.svg"
;
