export type Icons =
  | "appointments.svg"
  | "arrow.svg"
  | "calendar.svg"
  | "cancelled.svg"
  | "check.svg"
  | "check-circle.svg"
  | "close.svg"
  | "email.svg"
  | "loader.svg"
  | "logo-full.svg"
  | "logo-icon.svg"
  | "MediMeet.svg"
  | "pending.svg"
  | "upload.svg"
  | "user.svg"
;
export type ImagesFiles =
  | "admin.png"
  | "appointment-img.png"
  | "appointments-bg.png"
  | "cancelled-bg.png"
  | "dr-cameron.png"
  | "dr-cruz.png"
  | "dr-green.png"
  | "dr-lee.png"
  | "dr-livingston.png"
  | "dr-peter.png"
  | "dr-powell.png"
  | "dr-remirez.png"
  | "dr-sharma.png"
  | "onboarding-img.png"
  | "pending-bg.png"
  | "register-img.png"
;
